site_name: GraphKB Python
nav:
  - Home: index.md
  - Reference:
      - graphkb: reference/graphkb/__init__.md
      - graphkb.genes: reference/graphkb/genes.md
      - graphkb.match: reference/graphkb/match.md
      - graphkb.util: reference/graphkb/util.md
      - graphkb.vocab: reference/graphkb/vocab.md
theme:
  name: "material"
repo_url: https://svn.bcgsc.ca/bitbucket/projects/DAT/repos/graphkb_python
repo_name: Bitbucket
site_dir: build-docs